name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: '/' # Path to your app’s code
          api_location: 'api' # Path to your API code (if any)
          output_location: 'build' # Path to your build output directory
          deployment_action: 'upload' # Specify the action to take: 'upload' or 'deploy'
